//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bill()
        {
            this.bill_items = new HashSet<bill_items>();
        }
    
        public int id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<System.DateTime> bill_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill_items> bill_items { get; set; }
        public virtual customer customer { get; set; }
        public virtual employee employee { get; set; }
    }
}
